# Generated by Django 2.0.13 on 2020-11-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='mail',
            field=models.CharField(default='', max_length=20),
        ),
    ]
