# Generated by Django 2.0.13 on 2020-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_logindb_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='profilesetting',
            field=models.CharField(default='', max_length=8),
        ),
    ]
