# Generated by Django 2.0.13 on 2021-06-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_auto_20201114_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logindb',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
