# Generated by Django 2.0.13 on 2021-06-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_auto_20210619_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logindb',
            options={},
        ),
    ]
